### ISSUE TITLE
Week 4; Accounts and Logins

### ISSUE THREAD

**Issue by KoolKidKai** [KoolKidKai/Siuuuu#25]
**Must add static files and config files first**
- [ ] Hack #1; Phone number to authentication screen

- [ ] Hack #2; Logout to CRUD screen
![image](https://user-images.githubusercontent.com/89219634/162525444-471b162e-382c-423b-89ce-e0c8a2d46048.png)

- [ ] Hack #3; Add login__required to other part of site
